#ifndef ROBOTMAP_H
#define ROBOTMAP_H

//SHOOTER
#define SHOOTER_ENCODER_PORT 1,2
#define SHOOTER_MOTOR1_PORT 1
#define SHOOTER_MOTOR2_PORT 2

//CHASSIS
#define CHASSIS_TALON_TL_PORT 3
#define CHASSIS_TALON_TR_PORT 4
#define CHASSIS_TALON_BL_PORT 5
#define CHASSIS_TALON_BR_PORT 6
#define CHASSIS_GYRO_PORT 1

//STACK
#define STACK_DOUBLE_SOLENOID_PORT_F 1
#define STACK_DOUBLE_SOLENOID_PORT_R 2
#define STACK_TALON_PORT 1
#define STACK_MS_PORT 3

// CAMERA
#define CAMERA_SERVO_VERTICAL_PORT 9 
#define CAMERA_RELAY_PORT 2

// SHOOTER LIFT
#define SHOOTERLIFT_SOLENOID_F 3
#define SHOOTERLIFT_SOLENOID_R 4

// COMPRESSOR
#define COMPRESSOR_PRESSURE_SWITCH 4
#define COMPRESSOR_RELAY 1

//!!
#define IS_GITLITZ_KAFOT true
#define VISION ;
#define highfive high = 5
//!!

#endif
